#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tuan1314.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QL_BaiHat")]
	public partial class dbBaiHatDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_BaiHat(tbl_BaiHat instance);
    partial void Updatetbl_BaiHat(tbl_BaiHat instance);
    partial void Deletetbl_BaiHat(tbl_BaiHat instance);
    #endregion
		
		public dbBaiHatDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["QL_BaiHatConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbBaiHatDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbBaiHatDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbBaiHatDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbBaiHatDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_BaiHat> tbl_BaiHats
		{
			get
			{
				return this.GetTable<tbl_BaiHat>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_BaiHat")]
	public partial class tbl_BaiHat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaBH;
		
		private string _TenBH;
		
		private int _MaTL;
		
		private int _MaNS;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaBHChanging(int value);
    partial void OnMaBHChanged();
    partial void OnTenBHChanging(string value);
    partial void OnTenBHChanged();
    partial void OnMaTLChanging(int value);
    partial void OnMaTLChanged();
    partial void OnMaNSChanging(int value);
    partial void OnMaNSChanged();
    #endregion
		
		public tbl_BaiHat()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBH", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaBH
		{
			get
			{
				return this._MaBH;
			}
			set
			{
				if ((this._MaBH != value))
				{
					this.OnMaBHChanging(value);
					this.SendPropertyChanging();
					this._MaBH = value;
					this.SendPropertyChanged("MaBH");
					this.OnMaBHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenBH", DbType="NVarChar(50)")]
		public string TenBH
		{
			get
			{
				return this._TenBH;
			}
			set
			{
				if ((this._TenBH != value))
				{
					this.OnTenBHChanging(value);
					this.SendPropertyChanging();
					this._TenBH = value;
					this.SendPropertyChanged("TenBH");
					this.OnTenBHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTL", DbType="Int NOT NULL")]
		public int MaTL
		{
			get
			{
				return this._MaTL;
			}
			set
			{
				if ((this._MaTL != value))
				{
					this.OnMaTLChanging(value);
					this.SendPropertyChanging();
					this._MaTL = value;
					this.SendPropertyChanged("MaTL");
					this.OnMaTLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNS", DbType="Int NOT NULL")]
		public int MaNS
		{
			get
			{
				return this._MaNS;
			}
			set
			{
				if ((this._MaNS != value))
				{
					this.OnMaNSChanging(value);
					this.SendPropertyChanging();
					this._MaNS = value;
					this.SendPropertyChanged("MaNS");
					this.OnMaNSChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
